In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv("C:/Users/anand/Downloads/height-weight.csv")

In [3]:
df.head()

Height  Weight
0    1.47   52.21
1    1.50   53.12
2    1.52   54.48
3    1.55   55.84
4    1.57   57.20

In [6]:
df.isna().any() # Data doesn't have ant NANs

Height    False
Weight    False
dtype: bool

In [9]:
height=df.Height.values[:,np.newaxis]
weight=df.Weight.values
height


array([[1.47],
       [1.5 ],
       [1.52],
       [1.55],
       [1.57],
       [1.6 ],
       [1.63],
       [1.65],
       [1.68],
       [1.7 ],
       [1.73],
       [1.75],
       [1.78],
       [1.8 ],
       [1.83]])

In [11]:
weight

array([52.21, 53.12, 54.48, 55.84, 57.2 , 58.57, 59.93, 61.29, 63.11,
       64.47, 66.28, 68.1 , 69.92, 72.19, 74.46])

In [12]:
max_Height = height.max()
min_Height = height.min()
normalised_Height = (height - min_Height) / (max_Height - min_Height)
normalised_Height

array([[0.        ],
       [0.08333333],
       [0.13888889],
       [0.22222222],
       [0.27777778],
       [0.36111111],
       [0.44444444],
       [0.5       ],
       [0.58333333],
       [0.63888889],
       [0.72222222],
       [0.77777778],
       [0.86111111],
       [0.91666667],
       [1.        ]])

In [13]:
max_Weight = weight.max()
min_Weight = weight.min()
normalised_Weight = (weight - min_Weight) / (max_Weight - min_Weight)
normalised_Weight

array([0.        , 0.04089888, 0.10202247, 0.16314607, 0.22426966,
       0.2858427 , 0.34696629, 0.40808989, 0.48988764, 0.55101124,
       0.63235955, 0.7141573 , 0.79595506, 0.89797753, 1.        ])

In [14]:
from sklearn.linear_model import LinearRegression
alg = LinearRegression()
alg.fit(height, weight)

LinearRegression()

In [21]:
knownvalue = float(input("Enter the value of height in metres:"))
findvalue= alg.predict([[knownvalue]])
print("When the height is",knownvalue,"that weight is",findvalue)

Enter the value of height in metres:1.7
When the height is 1.7 that weight is [65.1007612]


In [23]:
df["Predicted Values of Weight(kg)"] = alg.predict(height)

In [24]:
df.head()

Height  Weight  Predicted Values of Weight(kg)
0    1.47   52.21                       51.008158
1    1.50   53.12                       52.846324
2    1.52   54.48                       54.071768
3    1.55   55.84                       55.909933
4    1.57   57.20                       57.135377

### Model Score

In [28]:
from sklearn.metrics import r2_score
accuracy = r2_score(weight , alg.predict(height))
print("Model Accuracy = " , accuracy*100, "%")

Model Accuracy =  98.91969224457968 %
